language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
  - sudo apt-get update
  - sudo apt-get install csstidy libxml2-dev libxslt-dev
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
script:
  - make test
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5
branches:
  only:
    - develop
notifications:
  irc: "irc.freenode.org#django-compressor"
